apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260613-155222-fbk0gide18wm-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260613-155222-fbk0gide18wm.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260613-155222-fbk0gide18wm-service
            port:
              number: 80
